/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.userinterface.legalEntity;

import app.utils.CommonUtils;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author PC
 */
public class starControl extends javax.swing.JPanel {

    int finalRate=1,size=30;
    private List<JLabel> starList;
    
    /**
     * Creates new form starControl
     */
    public starControl(int rating, int size,boolean readonly) {
        initComponents();
        this.size = size;
        starList= new ArrayList<>();
        for(int count =1;count <= 5;count++){
            JLabel label = new JLabel();
            label.setPreferredSize(new Dimension(size,size));
            label.setToolTipText(count+"");
            if(!readonly){
            label.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    super.mouseClicked(e); //To change body of generated methods, choose Tools | Templates.
                    JLabel label = (JLabel)e.getSource();
                    int r = Integer.parseInt(label.getToolTipText());
                    updateRating(r);
                    finalRate = r;
                }
                
            });
            }
            rateGrid.add(label);
            starList.add(label);
        }
        
        
        updateRating(rating);
    }

    public void updateRating(int rate){
        
        this.finalRate = rate;
        try {
            int count = 0;
            for(JLabel l: starList){
                if(count<rate){
                    CommonUtils.initPicPanel("src/app/images/starFilled.png", l);
                }
                else{
                    CommonUtils.initPicPanel("src/app/images/star.png", l);
                }
                count++;
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        
    }
    
    public int getRating(){
        return finalRate;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rateGrid = new javax.swing.JPanel();

        setOpaque(false);

        rateGrid.setOpaque(false);
        rateGrid.setLayout(new java.awt.GridLayout(0, 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rateGrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rateGrid, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel rateGrid;
    // End of variables declaration//GEN-END:variables
}
