/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.userinterface.court;

import app.business.LoginAction;
import app.data.Session;
import app.data.directories.Directory;
import app.data.org.Court;
import app.entities.user.Clerk;
import app.entities.user.CourtAdmin;
import app.entities.user.Judge;
import app.entities.user.Lawyer;
import app.entities.user.StateBarAssoAdmin;
import app.entities.workqueues.CaseFileRequest;
import app.entities.workqueues.LawyerApprovalRequest;
import app.entities.workqueues.StateBarAssoWorkQueue;
import app.entities.workqueues.WorkItem;
import app.userinterface.BasePanel;
import app.userinterface.MainFrame;
import app.userinterface.clerk.AssignJudgeDialog;
import app.userinterface.common.CustomPanel;
import app.userinterface.common.HeaderPanel;
import app.userinterface.sba.ViewSBARequestsPanel;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arele
 */
public class CourtWelcomePanel extends CustomPanel {

    /**
     * Creates new form CourtPanelNew
     */
    CourtAdmin courtadmin;
    Directory<Integer , Judge> judgeDir;
    Court c;
    
    public CourtWelcomePanel() {
        initComponents();
        this.makeTransparent(this);
        courtadmin = (CourtAdmin) Session.getUserAccount().getUser();
        c = (Court) courtadmin.getParent();
        populateTable();
        populateClerkTable();
        headerPanel.add(new HeaderPanel(Session.getUserAccount(), this, "Court"));
    }
    
    public void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) judgetable.getModel();
        model.setRowCount(0);
        for(Judge j: c.getJudgeDirectory().getAllEntries()){
            Object[] row = new Object[3];
            row[0] = j.getName();
            row[1] = j.getEmail();
            row[2] = j.getAccount().getUsername();
            model.addRow(row);
        }
    }
    
    public void populateClerkTable(){
    
        DefaultTableModel model = (DefaultTableModel) clerktable.getModel();
        model.setRowCount(0);
        for(Clerk cl: c.getClerkDirectory().getAllEntries()){
            Object[] row = new Object[3];
            row[0] = cl.getName();
            row[1] = cl.getEmail();
            row[2] = cl.getAccount().getUsername();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        containerpanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        judgetable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        addjudgebtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        clerktable = new javax.swing.JTable();
        addclerkbtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(878, 623));

        headerPanel.setLayout(new javax.swing.BoxLayout(headerPanel, javax.swing.BoxLayout.LINE_AXIS));

        judgetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Judge Name", "Judge Email", "Judge Username"
            }
        ));
        jScrollPane1.setViewportView(judgetable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 853, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        addjudgebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/path6261.png"))); // NOI18N
        addjudgebtn.setText("Add Judge to the Court");
        addjudgebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjudgebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addjudgebtn)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addjudgebtn)
                .addGap(134, 134, 134)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Judges", jPanel3);

        clerktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clerk Name", "Clerk Email", "Clerk Username"
            }
        ));
        jScrollPane2.setViewportView(clerktable);

        addclerkbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/images/path6261.png"))); // NOI18N
        addclerkbtn.setText("Add Clerk to the Court");
        addclerkbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addclerkbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addclerkbtn)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addclerkbtn)
                .addGap(223, 223, 223))
        );

        jTabbedPane1.addTab("Clerks", jPanel4);

        javax.swing.GroupLayout containerpanelLayout = new javax.swing.GroupLayout(containerpanel);
        containerpanel.setLayout(containerpanelLayout);
        containerpanelLayout.setHorizontalGroup(
            containerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        containerpanelLayout.setVerticalGroup(
            containerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(containerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(containerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addjudgebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjudgebtnActionPerformed
        // TODO add your handling code here:
                    
            AddJudgePopUp dialog = new AddJudgePopUp(c.getJudgeDirectory(),MainFrame.self,true);
           dialog.setSaveBtnListner(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    populateTable();
                }
            });
           
//            dialog.getContentPane().add(panel);
            
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            Point middle = new Point(screenSize.width / 2, screenSize.height / 2);
            Point newLocation = new Point(middle.x - (dialog.getWidth() / 2) - 200,
            middle.y - (dialog.getHeight() / 2) - 200);

            dialog.setLocation(newLocation);
            dialog.pack();
            dialog.setVisible(true);
    }//GEN-LAST:event_addjudgebtnActionPerformed

    private void addclerkbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addclerkbtnActionPerformed
        // TODO add your handling code here:
        AddClerkPopup dialog = new AddClerkPopup(c.getClerkDirectory(),MainFrame.self,true);
        
        dialog.setSaveBtnListner(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    populateClerkTable();
                }
            });
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            Point middle = new Point(screenSize.width / 2, screenSize.height / 2);
            Point newLocation = new Point(middle.x - (dialog.getWidth() / 2) - 200,
            middle.y - (dialog.getHeight() / 2) - 200);

            dialog.setLocation(newLocation);
            dialog.pack();
            dialog.setVisible(true);
    }//GEN-LAST:event_addclerkbtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addclerkbtn;
    private javax.swing.JButton addjudgebtn;
    private javax.swing.JTable clerktable;
    private javax.swing.JPanel containerpanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable judgetable;
    // End of variables declaration//GEN-END:variables
}
